"""one active session per user, not just open

Revision ID: 0eab2e72c700
Revises: a7fa0097abfd
Create Date: 2026-07-22 15:16:42.721012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eab2e72c700'
down_revision: Union[str, None] = 'a7fa0097abfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_work_sessions_one_open_per_user', table_name='work_sessions', sqlite_where=sa.text('ended_at IS NULL'))
    op.create_index('ux_work_sessions_one_active_per_user', 'work_sessions', ['user_id'], unique=True, sqlite_where=sa.text("status = 'active' AND ended_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_work_sessions_one_active_per_user', table_name='work_sessions', sqlite_where=sa.text("status = 'active' AND ended_at IS NULL"))
    op.create_index('ux_work_sessions_one_open_per_user', 'work_sessions', ['user_id'], unique=1, sqlite_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###
