"""initial schema

Revision ID: a7fa0097abfd
Revises: 
Create Date: 2026-07-22 12:56:47.018363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.tz


# revision identifiers, used by Alembic.
revision: str = 'a7fa0097abfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.tz.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('day_start_time', sa.Time(), nullable=False),
    sa.Column('created_at', app.tz.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.tz.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='ux_projects_user_name')
    )
    op.create_table('schedule_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('block_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_start', app.tz.UTCDateTime(), nullable=False),
    sa.Column('planned_end', app.tz.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.tz.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.tz.UTCDateTime(), nullable=False),
    sa.Column('completed_at', app.tz.UTCDateTime(), nullable=True),
    sa.Column('skipped_at', app.tz.UTCDateTime(), nullable=True),
    sa.Column('cancelled_at', app.tz.UTCDateTime(), nullable=True),
    sa.Column('rescheduled_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['rescheduled_from_id'], ['schedule_blocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedule_blocks_user_planned_start', 'schedule_blocks', ['user_id', 'planned_start'], unique=False)
    op.create_table('task_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_block_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', app.tz.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_block_id'], ['schedule_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_block_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.tz.UTCDateTime(), nullable=False),
    sa.Column('ended_at', app.tz.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.tz.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.tz.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_block_id'], ['schedule_blocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_work_sessions_one_open_per_user', 'work_sessions', ['user_id'], unique=True, sqlite_where=sa.text('ended_at IS NULL'))
    op.create_table('pause_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_session_id', sa.Integer(), nullable=False),
    sa.Column('started_at', app.tz.UTCDateTime(), nullable=False),
    sa.Column('ended_at', app.tz.UTCDateTime(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', app.tz.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pause_events')
    op.drop_index('ux_work_sessions_one_open_per_user', table_name='work_sessions', sqlite_where=sa.text('ended_at IS NULL'))
    op.drop_table('work_sessions')
    op.drop_table('task_items')
    op.drop_index('ix_schedule_blocks_user_planned_start', table_name='schedule_blocks')
    op.drop_table('schedule_blocks')
    op.drop_table('projects')
    op.drop_table('app_settings')
    op.drop_table('users')
    # ### end Alembic commands ###
